# -*- coding: utf-8 -*-
"""Classlar ile Banka Hesabı Kontrolü.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_YMVFmGfGMcpJcTJRG3ChUlzkFHkn78
"""

BankaHesabı = 0

class BankaHesabi:
    def __init__(self, hesapNumarasi,bakiye = 0):
        self.hesapNumarasi = hesapNumarasi
        self.bakiye = bakiye

    def para_yatir(self,miktar):

        self.bakiye+=miktar
        print(self.bakiye)
    def para_cek(self,miktar):
        self.bakiye-=miktar
        print(self.bakiye)

    def bakiyegoster(self):
        print(self.bakiye)

hesaplar = {}

while True:
    print("1-Banka Hesabı Aç")
    print("2-Para Yatır")
    print("3-Para Çek")
    print("4-Bakiye Göster")
    print("5-Çıkış")
    choise = int(input("Lütfen yapılacak işlemi seçin"))
    if choise ==1:
        hesapNumarasi = int(input("Hesap numarası giriniz:"))
        if hesapNumarasi in hesaplar:
            print("Bu hesap mevcur")
        else:
            hesaplar[hesapNumarasi]=BankaHesabi(hesapNumarasi)
            print("Hesap oluşturuldu")
    elif choise == 2:
        hesapNumarasi = int(input("Hesap numarasını girin"))
        if hesapNumarasi in hesaplar:
            miktar = int(input("Yatırılacak miktarı girin:"))
            hesaplar[hesapNumarasi].para_yatir(miktar)
        else:
            print("Hesap bulunamadı")
    elif choise == 3:
        if hesapNumarasi in hesaplar:
            miktar = int(input("Çekilecek miktarı girin:"))
            hesaplar[hesapNumarasi].para_cek(miktar)
        else:
            print("Hesap bulunamadı")
    elif choise == 4:
        hesapNumarasi = int(input("Hesap numarası giriniz:"))
        if hesapNumarasi in hesaplar:
            hesaplar[hesapNumarasi].bakiyegoster()
        else:
            print("Hesap bulunamadı")

    else:
        print("Çıkış yapılıyor...")
        break

